home:
    index: "首页"
bingli_infos:
    index: "病例讨论列表"
    new: "发表病例讨论"
    show: "病例讨论"
    edit: "修改病例讨论"
    tagged: "搜索病例标签"
    search: '搜索病例'
    query: '病例搜索结果'
users:
    new: '用户注册'
    create: '用户注册'
    forgot: "重设密码"
    index: '医生列表'
search:
    do_search: "病例讨论列表"
bingli_comments:
    new: "发表讨论"
    create: "发表讨论"
    edit: "编辑讨论"
    update: "编辑讨论"
meet:
    index: "会议列表"
    input: "发表会议"
    showone: "查看会议"
groups:
    index: "圈子列表"
    new: "新建圈子"
    show: "圈子"
    participate: "我参与的圈子"
sessions:
    new: "用户登录"
user:
    account: "帐户资料修改"
    pass_change: "密码修改"
    index: "个人帐户"
blog_posts:
    new: "发表博文"
    index: "博客列表"
    show: "博文浏览"
    tagged: "博客标签列表"
forum_topics:
    index: "经验交流"
photo_manager:
    index: "图库列表"
messages:
    index: "个人消息"
    show: "查看消息"
    new: "写消息"
events:
    index: "活动列表"
    new: "创建活动"
    participate: "我参与的活动"
invites:
    index: '邀请列表'
    new: '发送邀请'
    show: '邀请信息'
    create: '发送邀请'
events:
    index: '活动列表'
    show: '活动详情'
    new: '创建活动'
    create: '创建活动'
bug_reports:
    index: '问题建议列表'
    show: '问题建议内容'
    new: '提交问题或建议'
    create: '提交问题或建议'
tags:
    index: '标签列表'
    show: '标签'
    